
services:
  mongodb:
    image: mongo:latest
    container_name: car-tuning-crm-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=car-tuning-crm

volumes:
  mongodb_data: 